[package]
name = "fuse_mt"
version = "0.5.1"
authors = ["William R. Fraser <wfraser@codewise.org>"]
repository = "https://github.com/wfraser/fuse-mt"
description = "A higher-level FUSE filesystem library with multi-threading and inode->path translation."
categories = ["filesystem"]
keywords = ["fuse", "filesystem"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
async-trait = "0.1.42"
fuse = "0.3.1"
libc = "0.2"
log = "0.4"
time = "0.1"

[dependencies.tokio]
version = "1.0.1"
features = ["rt", "rt-multi-thread"]

[features]
default = []
# tokio-io = ["tokio/io-driver"]
tokio-time = ["tokio/time"]

[workspace]
members = [".", "example"]
